CREATE DATABASE customer_behavior;

use customer_behavior;
select * from customer limit 3;

#Q1. What is the total revenue generated by male vs female customers
select gender, sum(purchase_amount) as revenue from customer
group by gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount from customer
where discount_applied="Yes" 
and purchase_amount>( select avg(purchase_amount) from customer);

#Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),1) as avg  from customer
group by item_purchased
order by avg desc
limit 5;
#Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select  shipping_type,round(avg(purchase_amount)) from customer
where shipping_type in ("Express","Standard")
group by shipping_type;

#Q5. Do subscribed customers spend more?Compare average spend and total revenue between subscribers and non-subscribers
select count(customer_id),subscription_status,
avg(purchase_amount) as average_spend ,sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue desc;

#6. Which 5 products have the highest percentage of purchases with discounts applied?
select  item_purchased,
round(sum(case when discount_applied="Yes" then 1 else 0 end)*100.0/count(*),2) as discount_percentage
from customer
group by item_purchased
order by discount_percentage desc
limit 5;

#Q7. Segment customers into new,returning, and loyal based on their total number of 
#previous purchases, and show the count of each segment

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,count(*) from customer
where previous_purchases>5
group by subscription_status;

#Q10. What is the revenue contribution of each age group?
select age,sum(purchase_amount) as revenue_contribution from customer
group by age

